[package]
name = "srms-app"
version = "1.0.0"
description = "Student Result Management System"

[dependencies]
"php/php" = "8.2"

[[module]]
name = "main"
source = "."

[fs]
"/app" = "."

[[command]]
name = "start"
module = "main"
runner = "https://webc.org/runner/php"

[env]
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = ""
MYSQL_DATABASE = "srms_db"